### ISSUE TITLE
Hutch maintains stale database connection when DB goes down

### ISSUE THREAD

**Issue by lukebyrne** [gocardless/hutch#107]
Hi,

We have come across an issue in production
1. Our DB goes down for any reason
2. Our app sends a message to RabbitMQ to be consumed, the subsequent worker will require an ActiveRecord model to do some DB work
3. The Hutch worker loop has an rescue exception and just carries on pulling messages of queues (as it should do). From my reading of the exception handler it sends back a nack message to RabbitMQ which I believe we are then deadletter queuing
4. Our DB comes back up
5. Any Hutch worker thats needs to use an ActiveRecord model to do some DB work now has stale connections, and so the message that gets pulled off the queue will raise an exception and be nack'ed

I am guessing that this is possibly an issue that GoCardless will have come across in its use of Hutch (which by the way is a wonderful library, thankyou).

Can you offer any guidance or war stories on whether you have come across this, and if so how you dealt with it.

If not can you just offer some pleasant suggestions?

Cheers,

Luke

**Comment by luugiathuy** [comment]
@lukebyrne may I know how did you handle this issue for your case?

**Comment by bumi** [comment]
maybe helpful: https://github.com/basement-io/hutch-error-handlers-reconnect-active-record
