### ISSUE TITLE
Issue with Hutch.publish and Sidekiq (celluloid)

### ISSUE THREAD

**Issue by thibaudgg** [gocardless/hutch#114]
We're publishing Hutch message for Sidekiq jobs (using celluloid threads/actors), when we restart our workers (i.e. after a deploy) we often got this error for a short time:

`NoMethodError - undefined method `publish' for nil:NilClass` on `Hutch::Brocker` class [line 170](https://github.com/gocardless/hutch/blob/v0.9.0/lib/hutch/broker.rb#L170).

My guess is that after restart a many job try to connect and publish around the same time and `Hutch.connected?` is returning `true` before than `Hutch::Broker@exchange` instance var is set properly making the second publish fail.

Any ideas about how to fix that?

Note: We're connecting with `Hutch.connect(enable_http_api_use: false)` from Sidekiq, but I don't think that make any difference.

**Comment by Bivek** [comment]
@thibaudgg, @michaelklishin I did the same thing as @thibaudgg suggested making a hutch connection on sidekiq server config however; right after the deployment it starts to throw `NoMethodError - undefined method 'publish' for nil:NilClass`. But everything start to work well when I do a manual restart of sidekiq workers.

**Comment by tobmatth** [comment]
Same here. @thibaudgg We are also connecting during Sidekiq server initialization, but that does not seem to do the trick. Did you never ever see this issue again?

**Comment by michaelklishin** [comment]
@tobmatth I don't know how Sidekiq initialises but synchronising calls to `Hutch.connect` in your code should do the trick.
