### ISSUE TITLE
Multiple consumers for the same event (fanout exchange)

### ISSUE THREAD

**Issue by krisleech** [gocardless/hutch#120]
From my initial tests with Hutch it seems that if I have multiple consumers with the same routing key (topic) then only one consumer gets the events, i.e. round robin.

To allow multiple consumers of the same topic to receive all messages the exchange needs to be a fanout type exchange.

Is there any support for this in Hutch?

I see you can set the exchange so one possibility is to manually create a fanout exchange (outside of Hutch) and use that in the producers and consumers.

**Comment by rud** [comment]
If you want multiple consumers to handle the same message you'll need to make a queue for each, subscribed to the same topic. That way Rabbitmq will duplicate the message unto each queue, and each queue can handle messages at their own pace. Or am I missing something?

**Comment by krisleech** [comment]
@rud thanks for the response. I am about to pick this work up again. Let me close the issue for now.
