### ISSUE TITLE
No output after setting the RabbitMQ API host

### ISSUE THREAD

**Issue by zedtux** [gocardless/hutch#129]
I'm using Docker and the rabbitmq image in order to use hutch.

Given the following command line:

    $ hutch --verbose \
          --mq-api-port "$RABBITMQ_PORT_15672_TCP_PORT" \
          --mq-host "$RABBITMQ_PORT_5672_TCP_ADDR" \
          --mq-port "$RABBITMQ_PORT_5672_TCP_PORT" \
          --mq-username "guest" \
          --mq-password "guest" \
          --require /dockerci/lib/dockerci/runner/service.rb

Here is the output:

    $ fig up
    Recreating dockercirunner_rabbitmq_1...
    Recreating dockercirunner_web_1...
    Attaching to dockercirunner_rabbitmq_1, dockercirunner_web_1
    rabbitmq_1 |
    rabbitmq_1 |               RabbitMQ 3.4.2. Copyright (C) 2007-2014 GoPivotal, Inc.
    rabbitmq_1 |   ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
    rabbitmq_1 |   ##  ##
    rabbitmq_1 |   ##########  Logs: /data/log/rabbit@11d90af0a52a.log
    rabbitmq_1 |   ######  ##        /data/log/rabbit@11d90af0a52a-sasl.log
    rabbitmq_1 |   ##########
    rabbitmq_1 |  completed with 6 plugins.
    web_1      | 2015-01-06T17:38:50Z 8 INFO -- hutch booted with pid 8
    web_1      | 2015-01-06T17:38:50Z 8 INFO -- requiring '/dockerci/lib/dockerci/runner/service.rb'
    web_1      | 2015-01-06T17:38:50Z 8 INFO -- connecting to rabbitmq (amqp://guest@172.17.0.189:5672/)
    web_1      | 2015-01-06T17:38:50Z 8 INFO -- connected to RabbitMQ at 172.17.0.189 as guest
    web_1      | 2015-01-06T17:38:50Z 8 INFO -- opening rabbitmq channel
    web_1      | 2015-01-06T17:38:50Z 8 INFO -- using topic exchange 'hutch'
    web_1      | 2015-01-06T17:38:50Z 8 INFO -- HTTP API use is enabled
    web_1      | 2015-01-06T17:38:50Z 8 INFO -- connecting to rabbitmq HTTP API (http://guest@localhost:15672/)
    web_1      | 2015-01-06T17:38:50Z 8 ERROR -- HTTP API connection error: connection refused - connect(2) for "localhost" port 15672
    web_1      | 2015-01-06T17:38:50Z 8 FATAL -- couldn't connect to HTTP API at http://guest@localhost:15672/
    web_1      | 2015-01-06T17:38:50Z 8 INFO -- hutch terminated due to an error
    dockercirunner_web_1 exited with code 1
    Gracefully stopping... (press Ctrl+C again to force)
    Stopping dockercirunner_rabbitmq_1...

But when I set the API host:

    $ hutch --verbose \
          --mq-api-host "$RABBITMQ_PORT_15672_TCP_ADDR" \
          --mq-api-port "$RABBITMQ_PORT_15672_TCP_PORT" \
          --mq-host "$RABBITMQ_PORT_5672_TCP_ADDR" \
          --mq-port "$RABBITMQ_PORT_5672_TCP_PORT" \
          --mq-username "guest" \
          --mq-password "guest" \
          --require /dockerci/lib/dockerci/runner/service.rb

Then here is the output:

    $ fig up
    Recreating dockercirunner_rabbitmq_1...
    Recreating dockercirunner_web_1...
    Attaching to dockercirunner_rabbitmq_1, dockercirunner_web_1
    rabbitmq_1 |
    rabbitmq_1 |               RabbitMQ 3.4.2. Copyright (C) 2007-2014 GoPivotal, Inc.
    rabbitmq_1 |   ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
    rabbitmq_1 |   ##  ##
    rabbitmq_1 |   ##########  Logs: /data/log/rabbit@7426ac1b8b17.log
    rabbitmq_1 |   ######  ##        /data/log/rabbit@7426ac1b8b17-sasl.log
    rabbitmq_1 |   ##########
    rabbitmq_1 |  completed with 6 plugins.

I don't understand why this happen. I can set/unset any other parameters, everything is fine but when I set the `--mq-api-host`, hutch is silent.

FYI: In case you don't know the Docker stuff and fig, they set the environment variables with the IP addresses and ports where the services are running.

**Comment by zedtux** [comment]
Ha and even if there's no output, hutch is working fine.

**Comment by michaelklishin** [comment]
Something flushes stdout, or maybe the total amount of output is lower than stdout buffer. In any case, what can Hutch do? Try flushing it manually in one of your consumers. Flushing after every log line is probably a no-go for us.

**Comment by zedtux** [comment]
Well now when I remove the `--require` option or give a file which is not a valid hutch consumer class I have the output.

@michaelklishin thank you for your answer but I should see at least the same output as in the first case, isn't it ?

**Comment by zedtux** [comment]
OK adding `$stdout.sync = true` in my `service.rb` file makes the logs working...
