### ISSUE TITLE
basic.get support

### ISSUE THREAD

**Issue by dr-fozzy** [gocardless/hutch#133]
Is there any way to use "pull api" as described [here](http://rubybunny.info/articles/queues.html#fetching_messages_when_needed_pull_api) in hutch? Especially I want to receive multiple messages from queue, do some stuff(like merge), and publish result in another queue.

**Comment by michaelklishin** [comment]
Hutch is built around `basic.consume`, not `basic.get`. I'm not sure how `basic.get` would work. You can still use it because Hutch is based on Bunny but the whole idea doesn't fit in very well.

**Comment by dr-fozzy** [comment]
Get it, thanx.
