### ISSUE TITLE
Release 0.14?

### ISSUE THREAD

**Issue by drewish** [gocardless/hutch#135]
Seems like a good time for a release. There's some [nice fixes](https://github.com/gocardless/hutch/compare/v0.13.0...master) in there and it's been 3 months since the last one.

The one I'd love to get into a stable release is the configurable `read_timeout` setting. With bunny 1.5+ I can't start my rails app if I'm on our VPN, for some reason it times out with the default of 5.

**Comment by michaelklishin** [comment]
I agree. Should be out in the next 24 hours.
