### ISSUE TITLE
Dead-letter-exchange support

### ISSUE THREAD

**Issue by midu** [gocardless/hutch#136]
I would like to be able to always and possibly automatically have a DLX for all my queues.

My understanding is that to do so, I'd need to specify an `x-dead-letter-exchange` attribute for each queue, with the name of the exchange I want to send my messages to.

Hutch::Cli seems to be what sets up the queues. I'm thinking a good place for this could be in the consumer, since each consumer has its own queue. 

Maybe something like this:

```rb
class MyHutchConsumer
  include Hutch::Consumer

  consume 'my.hutch.consumer', dlx: true

  # or we could 

  consume 'my.hutch.consumer', dlx: 'my.deadletter.exchange'
```

Is that something that would make sense?

My use case is this: I need to find a way to access my failed jobs, and possibly retry them if whatever made them fail is fixed. I don't really need a UI, especially since I think rabbitmq's UI would probably do a good enough job.

I was surprised to not see a default dlx exchange in rabbitmq, since it has so many default exchanges out of the box.

I am pretty new to the RabbitMQ world, so maybe this question makes no sense... I would appreciate any comment about this issue.

**Comment by michaelklishin** [comment]
You want a policy, see RabbitMQ documentation.
