### ISSUE TITLE
Improve bunny exceptions handling

### ISSUE THREAD

**Issue by lostie** [gocardless/hutch#137]
Quite recently I was using Hutch to publish some messages to RabbitMQ and I stopped the RabbitMQ server during that process (on purpose, for test purposes).

My application ended up getting the following exception:

```ruby
Bunny::ConnectionForced (Connection-level error: CONNECTION_FORCED - broker forced connection closure with reason 'shutdown')
```

My publisher implementation already handles `Hutch` [exceptions](https://github.com/gocardless/hutch/blob/master/lib/hutch/exceptions.rb)

I was wondering if `Hutch` should be handling `Bunny` [exceptions](https://github.com/ruby-amqp/bunny/blob/e4e98e7c3673f0e75ad55b7e47539920ca18eafd/lib/bunny/exceptions.rb) so that whoever is using `Hutch` does not need to know that `Hutch` is using `Bunny` under the hood.

@michaelklishin and @hutch-community : What's your thoughts on it?

**Comment by michaelklishin** [comment]
I find it unfortunate that Hutch had to re-invent pretty much the same exceptions but since it already has an exception for publishing errors, we can do that.

The exception you are seeing is not thrown on publish, though. It is RabbitMQ closing connection because it is shutting down.
