### ISSUE TITLE
Hutch stopping after network failure

### ISSUE THREAD

**Issue by teodor-pripoae** [gocardless/hutch#143]
Hi,

Ocasionally there is a network failure which makes hutch stop. Is there any way to try to reconnect after network failure ?

I'm using hutch inside a vanilla ruby app, starting it with:

```
$ hutch --require config/boot.rb
```

```
E, [2015-03-24T01:10:47.332857 #1] ERROR -- #<Bunny::Session:70093678280760 events@mq.frkt.myapp.production:5672, vhost=/, hosts=[mq.frkt.myapp.production]>: Got an exception when receiving data: IO timeout when reading 7 bytes (Timeout::Error)
W, [2015-03-24T01:10:47.334018 #1]  WARN -- #<Bunny::Session:70093678280760 events@mq.frkt.myapp.production:5672, vhost=/, hosts=[mq.frkt.myapp.production]>: Recovering from a network failure...
2015-03-24T01:10:47Z 1 INFO -- hutch shut down gracefully
```

LE: will it be a solution to wrap hutch inside something like supervisor.d with autorestart ? Is any kind of reconnect built in into hutch ?

**Comment by michaelklishin** [comment]
Bunny support reconnection. Something similar to retries can be added to `Hutch::CLI.run`. If you run Hutch via its command line runner and not as a Ruby library, having a tool that re-starts the process is a good idea for multiple reasons.
