### ISSUE TITLE
HTTP API Required?

### ISSUE THREAD

**Issue by jasoncox** [gocardless/hutch#145]
The HTTP API can be disabled for both:

Publishers:
```
Hutch.connect(enable_http_api_use: false)
```

And Consumers via config.yml:
```
enable_http_api_use: false
```

Is it required? What is it's purpose?

**Comment by michaelklishin** [comment]
It is used to list bindings. It is currently required, although at some point was attempted to made optional IIRC.

**Comment by jasoncox** [comment]
Should I expect to run in to some kind of trouble if I disable it everywhere? What functionality does that break?

**Comment by michaelklishin** [comment]
I'm pretty sure as things stand you will see a nil pointer exception. Other than that, Hutch maintains your bindings so if you somehow delete one of them, they are re-created. For that it needs to list them and that's only possible over the HTTP API.

**Comment by dkastner** [comment]
I've disabled HTTP api on all my consumers (because not all rmq providers enable it by default) and haven't seen any issues. Any time I've changed a queue name, they've been created automatically. I don't really think it's needed anymore. I was just checking here because I had the same question, whether I'm "doing it wrong."

**Comment by teodor-pripoae** [comment]
When you create a consumer, let's say `FailedPaymentConsumer` on routing key `gc.ps.payment.failed`, hutch will bind the `failed_payment_consumer` queue on this routing key. Later, if you change routing key, it will attempt to bind again on the new routing key leaving the old one there. HTTP API is used for finding which routing keys are not used anymore and unbinding the queue for that routing keys.

**Comment by dkastner** [comment]
I'm starting to think this kind of job is better handled by a separate "queue migrator" tool, especially when you get into managing all sorts of routing behaviors. While it's nice for very simple use cases to automatically manage queue settings, it'd be nice to have the whole thing be optional (which it already is AFAIK).
