### ISSUE TITLE
Good pattern to publish answer to temporary queue

### ISSUE THREAD

**Issue by starkovv** [gocardless/hutch#147]
Say I have facade (for front-end) microservice, which uses HTTP interface to talk to outside world and AMQP interface to talk inside application cluster (inter-service communication).

When facade microservice receives HTTP-request from the outside client, it then publishes event into RabbitMQ broker with the mark, that the response to that request should be delivered to the explicit temporary queue. And then it subscribes to that temporary queue waiting for the answer.

When an answer is arrived, facade will resend it as a HTTP response to the outside client.

The question is: what are some good patterns to publish an answer from hutch consumer to such temporary queue?

**Comment by michaelklishin** [comment]
Seems to be the same question as #34.

**Comment by gottfrois** [comment]
I had a similar use case. I use hutch to publish/subscribe to durable topics but I use bunny directly to respond to temporary queues. I wrote a blog post about this [here](http://www.codeids.com/2015/05/03/temp-queue-using-rabbitmq-and-web-stomp/).

**Comment by starkovv** [comment]
@gottfrois Images seems corrupted

**Comment by gottfrois** [comment]
oh really? let me fix that. Thx for the feedback
