### ISSUE TITLE
Routing key convention for inter-service requests

### ISSUE THREAD

**Issue by starkovv** [gocardless/hutch#148]
As mentioned in https://gocardless.com/blog/hutch-inter-service-communication-with-rabbitmq
```
All messages are assigned routing keys, which typically specify the originating service, the subject (noun) of the message, and an action (e.g. paysvc.mandate.transfer).
```

This is a good example of convention for service emitting event of its current activity.

Could you give an example of such convention for the service, that is *requesting* some information from another service, to make its job done?

1) Say, when the UserPasswordResetsService asks UsersService to check for `user` existence.

2) And then the second example, when UserPasswordResetsService asks MailerService to send email to given address.

Thanks in advance!

**Comment by michaelklishin** [comment]
# users.exists, users.user.exists
# mailer.deliver, mailer.email.deliver-to

**Comment by starkovv** [comment]
Simple.

Thanks.
