### ISSUE TITLE
Set timeout on re-queued messages

### ISSUE THREAD

**Issue by misha-slyusarev** [gocardless/hutch#161]
When my consumer loses connection to a database I would like to requeue all the messages I got and try to handle them later. But if I use requeue! method, I will get that message instantly back from Rabbit. 

Is it possible to put a timeout on either Hutch or RabbitMQ site in this situation?

I also asked about that on SO
http://stackoverflow.com/questions/31721520/hutch-rabbitmq-set-timeout-on-re-queued-messages

**Comment by michaelklishin** [comment]
Not without using [Scheduled delivery exchange](https://www.rabbitmq.com/blog/2015/04/16/scheduling-messages-with-rabbitmq/), or abusing [TTL](http://rabbitmq.com/ttl.html) and dead lettering.
