### ISSUE TITLE
Support for delayed message exchange

### ISSUE THREAD

**Issue by Bivek** [gocardless/hutch#173]
Sometimes we have a requirement where job needs to be pushed to queue after certain interval. For that we need to utilise delayed message exchange of rabbitmq.

**Comment by michaelklishin** [comment]
Sorry but Hutch is opinionated and assumes topic exchanges. You can publish to a delayed exchange with Bunny or use exchange-to-exchange bindings. I don't see how other exchange types would fit Hutch without turning it into something that looks like an (incomplete and opinionated) generic RabbitMQ client.
