### ISSUE TITLE
Using bunny on JRuby

### ISSUE THREAD

**Issue by gottfrois** [gocardless/hutch#176]
```
$ rvm list
=> jruby-1.7.19 [ x86_64 ]

$ gem install hutch
Please report a bug if this causes problems.
Fetching: carrot-top-0.0.7.gem (100%)
Successfully installed carrot-top-0.0.7
ERROR:  Error installing hutch:
	amq-protocol requires Ruby version >= 2.0.
```

This is because building the gem `pkg` using `gemspec` is done on the gem owner side and not on client side. Declaring platform dependencies in the gemspec will not ensure proper gem will be installed on the client gemset.

In order to do that you need to build the gem with native extensions so that ruby code is run on the client machine when he runs the `bundle install` command.

**Comment by michaelklishin** [comment]
I don't get it. Are you sure you run JRuby 9K? Earlier versions do not support Ruby 2.0-2.2. the error message says that is the problem.

**Comment by gottfrois** [comment]
Sorry about that, was not running JRuby 9K. But it does not change the issue since gemspec is not interpreted on the client machine, but when building the gem `pkg`.

```
$ rvm list
=> jruby-9.0.0.0.pre1 [ x86_64 ]

$ gem install hutch
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: i18n-0.7.0.gem (100%)
Successfully installed i18n-0.7.0
Fetching: activesupport-4.2.4.gem (100%)
Successfully installed activesupport-4.2.4
Fetching: multi_json-1.11.2.gem (100%)
Successfully installed multi_json-1.11.2
Fetching: carrot-top-0.0.7.gem (100%)
Successfully installed carrot-top-0.0.7
Fetching: amq-protocol-2.0.0.gem (100%)
Successfully installed amq-protocol-2.0.0
Fetching: bunny-2.2.0.gem (100%)
Successfully installed bunny-2.2.0
Fetching: hutch-0.19.0.gem (100%)
Successfully installed hutch-0.19.0
8 gems installed
```

**Comment by michaelklishin** [comment]
@gottfrois so what specifically do you suggest? I don't understand the "native gem" part. Hutch has no native or Java code, nor it has any need for it.

**Comment by teodor-pripoae** [comment]
@michaelklishin  When releasing the gem, you must build it for each platform (MRI and Jruby), then push both gem versions to rubygems.

Gemspec is evaluated at gem build time, so if you are building under MRI, it is evaluated for MRI, adding `bunny` as a dependency. If you are building under Jruby, it is evaluated as Jruby, adding `march_hare` as a dependency.

When `hutch` is added to gemfile, bundler will try to find `hutch` gem on rubygems for platform `java` first, then default to universal platform. Since it can not find `java` platform on rubygems, it uses the default gem built under MRI, using bunny as a dependency.

**Comment by gottfrois** [comment]
I have the exact same issue with a gem of mine. Trying to figure out the proper way to do this myself too. Like @teodor-pripoae just said, since gemspec is evaluated at gem build time, the only way to evaluate ruby code when the client run the `bundle install` command is to build native extensions.

I've tried to go that way using this `mkrf_conf.rb` as the extension:

```ruby
require 'rubygems'
require 'rubygems/command.rb'
require 'rubygems/dependency_installer.rb'
begin
  Gem::Command.build_args = ARGV
  rescue NoMethodError
end
inst = Gem::DependencyInstaller.new
begin
  if defined?(JRUBY_VERSION)
    inst.install "march_hare", "~> 2.13"
  else
    inst.install "bunny", "~> 2.2"
  end
  rescue
    exit(1)
end

f = File.open(File.join(File.dirname(__FILE__), "Rakefile"), "w")   # create dummy rakefile to indicate success
f.write("task :default\n")
f.close
```

While this works (only install bunny on `ruby` and `march_hare` on `jruby`), it will not put the gem in the gemfile.lock of rails app. Then if you try to require bunny or march_hare, it will tell you it's not available.

@teodor-pripoae I was not aware that bundler will first try to locate the java version on rubygems. So that means we can "build" the gem `pkg` on both platform but how can you push twice the "same" `pkg` on rubygems?

**Comment by teodor-pripoae** [comment]
You can build it without native extensions:

```bash
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
$ gem build hutch.gemspec
  Successfully built RubyGem
  Name: hutch
  Version: 0.19.0
  File: hutch-0.19.0.gem

$ ruby -v
jruby 9.0.0.0 (2.2.2) 2015-07-21 e10ec96 Java HotSpot(TM) 64-Bit Server VM 25.60-b23 on 1.8.0_60-b27 +jit [darwin-x86_64]
$ gem build hutch.gemspec
  Successfully built RubyGem
  Name: hutch
  Version: 0.19.0
  File: hutch-0.19.0-java.gem

$ ls hutch-*.gem
hutch-0.19.0-java.gem hutch-0.19.0.gem

$ gem push hutch-0.19.0.gem
$ gem push hutch-0.19.0-java.gem
```

**Comment by teodor-pripoae** [comment]
```
If you run bundle package under C Ruby, bundler will retrieve the version of nokogiri for the "ruby" platform. If you deploy to JRuby and run bundle install, bundler is forced to check to see whether a "java" platformed nokogiri exists.

Even though the nokogiri gem for the Ruby platform is technically acceptable on JRuby, it actually has a C extension that does not run on JRuby. As a result, bundler will, by default, still connect to rubygems.org to check whether it has a version of one of your gems more specific to your platform.

This problem is also not just limited to the "java" platform. A similar (common) problem can happen when developing on Windows and deploying to Linux, or even when developing on OSX and deploying to Linux.
```

From: http://bundler.io/man/bundle-package.1.html

**Comment by michaelklishin** [comment]
Thanks for the detailed explanation, I've [build and released](https://rubygems.org/gems/hutch) `0.19.0` on JRuby 9K:

```
gem install hutch
Fetching: march_hare-2.13.0-java.gem (100%)
Successfully installed march_hare-2.13.0-java
Fetching: carrot-top-0.0.7.gem (100%)
Successfully installed carrot-top-0.0.7
Fetching: multi_json-1.11.2.gem (100%)
Successfully installed multi_json-1.11.2
Fetching: thread_safe-0.3.5-java.gem (100%)
Successfully installed thread_safe-0.3.5-java
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: i18n-0.7.0.gem (100%)
Successfully installed i18n-0.7.0
Fetching: activesupport-4.2.4.gem (100%)
Successfully installed activesupport-4.2.4
Successfully installed hutch-0.19.0-java
8 gems installed
```

**Comment by gottfrois** [comment]
thanks @teodor-pripoae, also helped me fix my similar issue on my own gem

**Comment by rdubya** [comment]
@michaelklishin it looks like this issue may have popped up again.

When I try to install it on jruby less than 9k it gives the error:

```
ERROR:  Error installing hutch:
	amq-protocol requires Ruby version >= 2.0.
```

 When I try to install it on jruby 9k it installs bunny instead of march_hare:

```
$ gem install hutch
Fetching: i18n-0.7.0.gem (100%)
Successfully installed i18n-0.7.0
Fetching: thread_safe-0.3.5-java.gem (100%)
Successfully installed thread_safe-0.3.5-java
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: activesupport-4.2.5.2.gem (100%)
Successfully installed activesupport-4.2.5.2
Fetching: amq-protocol-2.0.1.gem (100%)
Successfully installed amq-protocol-2.0.1
Fetching: bunny-2.3.0.gem (100%)
Successfully installed bunny-2.3.0
Fetching: carrot-top-0.0.7.gem (100%)
Successfully installed carrot-top-0.0.7
Fetching: multi_json-1.11.2.gem (100%)
Successfully installed multi_json-1.11.2
Fetching: hutch-0.21.0.gem (100%)
Successfully installed hutch-0.21.0
9 gems installed
```

Is that the expected outcome after the latest release?

**Comment by michaelklishin** [comment]
@rdubya damn, so we need to publish on both MRI and JRuby forever now. OK, I've pushed a `0.21.0` gem built JRuby 9K.

```
gem install hutch
Fetching: i18n-0.7.0.gem (100%)
Successfully installed i18n-0.7.0
Fetching: thread_safe-0.3.5-java.gem (100%)
Successfully installed thread_safe-0.3.5-java
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: activesupport-4.2.5.2.gem (100%)
Successfully installed activesupport-4.2.5.2
Fetching: carrot-top-0.0.7.gem (100%)
Successfully installed carrot-top-0.0.7
Fetching: march_hare-2.16.0-java.gem (100%)
Successfully installed march_hare-2.16.0-java
Fetching: multi_json-1.11.2.gem (100%)
Successfully installed multi_json-1.11.2
Fetching: hutch-0.21.0-java.gem (100%)
Successfully installed hutch-0.21.0-java
8 gems installed
```

**Comment by rdubya** [comment]
I guess so. Thanks for taking care of it so quickly.
