### ISSUE TITLE
Increase number of consumers

### ISSUE THREAD

**Issue by paniko0** [gocardless/hutch#178]
Hi guys,

don't know if this is the right place to ask questions, but there's any way to improve the number of consumers on a queue when using Hutch?

Tried looking up the code and didn't find a thing.

**Comment by michaelklishin** [comment]
What do you mean by "os consumers"?

**Comment by paniko0** [comment]
Sorry, my bad. I meant "of consumers"

**Comment by michaelklishin** [comment]
Run N instances of Hutch process or create N consumer classes that share a queue.

Why do you want to use more consumers? In Hutch's case, it would hardly result in any concurrency improvement.

**Comment by hamiltop** [comment]
>  In Hutch's case, it would hardly result in any concurrency improvement.

Could you help me understand this? We want to run multiple consumers in order to scale our consumes horizontally, but we're seeing some form of contention between them.

**Comment by michaelklishin** [comment]
On CRuby consumers will not run in parallel and the entire Hutch instance would for the most part be limited by a single core.

There can be other reasons:

 * An overly conservative [prefetch value used](https://www.rabbitmq.com/confirms.html#channel-qos-prefetch-throughput) by said consumers
 * [Single shared queue throughput has a realistic limit](https://www.rabbitmq.com/queues.html#runtime-characteristics): use [PerfTest](https://rabbitmq.github.io/rabbitmq-perf-test/stable/htmlsingle/#basic-usage) to establish a baseline to compare against. Note that you can use PerfTest only to publish and Hutch-based consumers to consume, or vice versa.

I cannot suggest much more with the amount of information provided. Such discussions belong to the RabbitMQ mailing list.

**Comment by michaelklishin** [comment]
To be fair, on JRuby having more than one consumer on a shared queue can indeed be beneficial up to a point since message deliveries are dispatched concurrently with a per-channel ordering guarantee by the underlying RabbitMQ clients, March Hare (used on JRuby) and Bunny (CRuby).

So can be moving more time consuming parts to a thread pool or using any other concurrent programming approach available with a single consumer. The rest of the recommendations applies to all Ruby implementations.

**Comment by hamiltop** [comment]
I'm talking about running N processes, so I don't expect CRuby to be a bottleneck here. I'll explore the prefetch setting, thanks for the tip!

**Comment by michaelklishin** [comment]
Then my original comment above is not applicable. What your consumers do matters as well, if they all try to use a shared resource of some kind then it can be the limiting factor. Application and infrastructure level metrics can help narrow things down.
