### ISSUE TITLE
Prevent some configuration changes after running `Hutch.connect`

### ISSUE THREAD

**Issue by jesjos** [gocardless/hutch#189]
Today I spent some time debugging an issue that was caused by me doing this:

``` ruby
Hutch.connect
# ... 
Hutch::Config.set(:force_publisher_confirms, true)
Hutch.publish(blah)
```

This doesn't work because `.confirm_select` has to be called on the channel before calling `.wait_for_confirms`.

`.confirm_select` is only called in `Hutch.connect` if `force_publisher_confirms` is set. So setting this _after_ running `Hutch.connect` will cause `Hutch.publish` to fail with a nil error:

``` ruby
NoMethodError: undefined method `empty?' for nil:NilClass
    from /Users/jesjos/.rvm/gems/ruby-2.3.0/gems/bunny-2.2.2/lib/bunny/channel.rb:1812:in `block in wait_on_confirms_continuations'
    from /Users/jesjos/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    from /Users/jesjos/.rvm/gems/ruby-2.3.0/gems/bunny-2.2.2/lib/bunny/channel.rb:1811:in `wait_on_confirms_continuations'
    from /Users/jesjos/.rvm/gems/ruby-2.3.0/gems/bunny-2.2.2/lib/bunny/channel.rb:1434:in `wait_for_confirms'
    from /Users/jesjos/.rvm/gems/ruby-2.3.0/gems/hutch-0.20.0/lib/hutch/broker.rb:227:in `publish'
    from /Users/jesjos/.rvm/gems/ruby-2.3.0/gems/hutch-0.20.0/lib/hutch.rb:60:in `publish'
```

I'm thinking it would be nice if Hutch somehow failed early or at least warned about this. Maybe it would make sense to prevent some, or all, kinds of configuration changes once Hutch is connected.

I'd gladly provide a PR if and once an appropriate strategy is identified.

**Comment by olleolleolle** [comment]
Is this newly-released thing related? https://github.com/ruby-amqp/bunny/pull/428

**Comment by arthurmde** [comment]
I'm facing the same error even when I set the force_publisher_confirms before connecting...
```ruby                              
Hutch::Config.set(:force_publisher_confirms, true)                          
Hutch.connect                                                               
Hutch.publish(routing_key, payload)
```

Any ideas?

Thanks =)

**Comment by michaelklishin** [comment]
Two ideas:

 * Configure publisher confirms after connecting
 * Contribute a PR since this is open source software

**Comment by michaelklishin** [comment]
After reviewing #337 and considering what alternatives we have, I think this should be closed as "works as expected". Documentation improvements would be welcome, although I'm not 100% sure where to put them except for the `Hutch.connect` method reference docs.

The way Hutch sets up its topology assumes that all configuration is known before connection time. This makes sense: if you want to have full control, Hutch is not the right too for you.

We could introduce a "reconfigure" method but it would not be able to reconfigure most things without reconnecting, and that can be potentially disruptive. We could make `Hutch::Config.set` smarter but that would tie it to connections which makes no sense. #337 introduces a solution with a significant amount of overhead on the hot code path and I don't think every user should pay that price for one use case.

The current behavior makes most sense to me.
