### ISSUE TITLE
Cron job deletes connection

### ISSUE THREAD

**Issue by potato20** [gocardless/hutch#192]
Using the [whenever](https://github.com/javan/whenever) gem, I have a cron job that runs a rake task every 15 minutes. The rake task is very small and simple and only touches Redis, however, for reasons I o't understand, it causes my Rails app running in the background to delete its connection to rabbit mq. The server can then no longer send messages to rabbitmq.

Is this because the rake task and the rails app share the same connection pool, and the task wipes it when it finishes? I'm not sure what's happening exactly.

**Comment by michaelklishin** [comment]
`fork(2)` has a well known effect on open file descriptors and TCP sockets. We cannot suggest much without seeing RabbitMQ log files but I suspect that gem forks at some point.
