### ISSUE TITLE
Connections close by themselves after a while?

### ISSUE THREAD

**Issue by potato20** [gocardless/hutch#193]
I have a simple rails app on a staging server, served using passenger5+apache2.4 and when i start it up, RabbitMQ's connections tab shows two connections. I verify it's that server via the IP address that show sup. I'm guessing Hutch opens two separate connections? I run `Hutch.connect` from an initializer and I read my settings from a config yaml file.

Now the server is sitting behind an amazon elb, and after I leave it for about 5-10 minutes (i.e. the only requests hitting the server are the aws health checks, which get returned 200), RabbitMQ shows only 1 connection from that server. Then after another 5-10 minutes, it shows 0 connections! I then test this by hitting the Rails app at an endpoint that calls `Hutch.publish` and, as expected, no message is seen by my consumer or rabbitmq's admin console.

Can someone explain this or does it require more info about the staging environment? Is there something in the background that's causing this?

**Comment by michaelklishin** [comment]
@potato20 we cannot suggest much without seeing RabbitMQ log files but in 95% of cases it's the load balancer that closes connections that it considers to be stale or inactive. Enable [heartbeats](http://www.rabbitmq.com/heartbeats.html) with a timeout value of 10 or so, that will keep TCP load balancers with sane timeout values happy.

**Comment by michaelklishin** [comment]
By default heartbeat intervals are 580 seconds (prior to RabbitMQ 3.6.0) or 60 seconds (3.6.0 and later versions). Clients can override this value.

**Comment by potato20** [comment]
I wasn't aware elb closes tcp connections it was no business with? The idle timeout is at 60 seconds but i thought that only dealt with tcp connections between the server the the elb, not the server and external services??

Regardless, I was using rabbitmq 3.5.6, and setting heartbeat to 10 in the config did not stop the issue.

**Comment by michaelklishin** [comment]
@potato20 load balancers certainly can close connections they consider to be inactive. Again, we can only speculate without seeing your code or RabbitMQ log files. Passenger forks processes and that affects open sockets (open file handles in general, actually), as [mentioned in Bunny documentation](http://rubybunny.info/articles/connecting.html#using_bunny_with_passenger). So make sure you connect in the worker process.

**Comment by potato20** [comment]
I've followed Bunny's docs and established the connection in the worker process. It's been two hours doing just elb health checks and some serving, and the connections are stable, I'm guessing that was the solution. Perhaps it's worth mentioning how to connect Hutch for servers like passenger.

Thanks!
