### ISSUE TITLE
Handling Exceptions (not StandardError)

### ISSUE THREAD

**Issue by dkastner** [gocardless/hutch#195]
We tried stress testing our hutch workers and one of the tests was to see what happens when you `raise Exception`. It turns out the hutch/bunny worker thread halts. Since the connection is left open to RabbitMQ (preserving the heartbeat), the message handled by the worker thread disappears into a black hole.

Now, it is bad practice to `raise Exception` or any of its subclasses  other than `StandardError` but in the rare event that a novice coder does, it would be nice for hutch to handle this. Would it make sense to either `rescue Exception` or set `Thread.abort_on_exception = true`? I noticed that the bunny docs use `Thread.abort_on_exception` http://rubybunny.info/articles/queues.html#registering_consumer_instances

**Comment by michaelklishin** [comment]
Bunny docs use it only as an example. Consumers are supposed to handle their exceptions. And it's not true that deliveries "disappear into a black hole". With manual acknowledgements if you force a channel closure, they will be re-queued.

What's the point of throwing an exception from a delivery handler? What part of the code do you expect to handle it? At best tools such as Hutch can provide a way to log/submit them somewhere.

**Comment by seamusabshere** [comment]
@michaelklishin @dkastner i would expect that individual hutch worker threads should have `#abort_on_exception = true`

**Comment by michaelklishin** [comment]
@seamusabshere which would be a lot like using `System.exit` on the JVM. Yeah, the road to hell is paved with good intentions.

Sorry, no library gets to decide if an unhandled exception can terminate your entire service.

**Comment by dkastner** [comment]
> Consumers are supposed to handle their exceptions

This is true, and I agree it's bad practice to `raise Exception`, but if someone does mistakenly do it, I'd rather prevent a thread dying than rely on programmers doing the right thing all the time.

>  it's not true that deliveries "disappear into a black hole" ... if you force a channel closure, they will be re-queued

In this case, I don't think the channel is closed, rather, the worker handling the message simply halts. Try this sample and hit CTL-C once you see thread 4 raise the exception.

``` ruby
threads = []

Thread.abort_on_exception = true

@keep_going = true

def good(n)
  Proc.new do
    while @keep_going do
      puts "AOK #{n}"
      sleep 1
    end
  end
end

def bad(n)
  Proc.new do
    3.times do
      puts "AOK #{n}"
      sleep 1
    end
    puts "OK GOING TO DIE NOW #{n}"
    sleep 1
    raise Exception, "this is so bad"
  end
end

threads << Thread.new(&good(1))
threads << Thread.new(&good(2))
threads << Thread.new(&good(3))

threads << Thread.new(&bad(4))

Signal.trap("INT") do |sig|
  @keep_going = false
  threads.map(&:join)
end

sleep 1 while true
```

Notice that you don't see any error output from thread 4 until you CTL-C

**Comment by dkastner** [comment]
So all I am suggesting, is that here https://github.com/gocardless/hutch/blob/master/lib/hutch/worker.rb#L121 instead of implicitly only handling `StandardError` and its subclasses, rescue `Exception` explicitly

**Comment by michaelklishin** [comment]
I understand that channels are not closed in the OP's case. The answer is still "consumers are supposed to handle their exceptions". And we are not going to set `Thread#abort_on_exception` on any threads created by Bunny or Hutch.

Handling `Exception` is OK with me but a surprising number of people oppose this idea (in general). I'd like to hear what @gocardless/backend thinks of this proposal.

**Comment by seamusabshere** [comment]
@michaelklishin https://github.com/orgs/gocardless/teams/backend @dkastner 

my concern is "zombie mode": an exception gets raised in a hutch worker thread, and the whole app just hangs silently

by setting `abort_on_exception`, we at least allow that exception to bubble up

by **not** setting `abort_on_exception`, we just have a zombie hutch - we're not helping anybody

i don't know if it's necessary to rescue anything

**Comment by michaelklishin** [comment]
@seamusabshere Hutch specifically could set `Thread#abort_on_exception` *but* we have absolutely no idea how Hutch can be used. It's certainly commonly embedded into Web apps for publishing, can be the case in other apps that consume. It is not a library's business to decide when apps should or should not be terminated.

Needless to say that forcing VM termination after an unhandled exception in a library such as Bunny would be a giant disservice to its users.

**Comment by seamusabshere** [comment]
@michaelklishin 

current state of hutch:

```ruby
t = Thread.new do
  raise Exception
end
sleep 1 # give it time to blow up
puts "zombie thread!"
sleep
```

better:

```ruby
begin
  t = Thread.new do
    sleep 1 # give me time to set abort_on_exception
    raise Exception
  end
  t.abort_on_exception = true
  sleep
rescue Exception
  puts "VM wasn't killed"
end
```

point is, `abort_on_exception` doesn't kill the VM, the surrounding application can rescue from it if it really wants

BUT hutch should not hide an exception inside of its threads, that is very unexpected

**Comment by michaelklishin** [comment]
@seamusabshere surrounding application might as well catch all exceptions in its delivery handlers. Oops, we've already listed this options twice above.

**Comment by seamusabshere** [comment]
@michaelklishin but if hutch launches threads without `abort_on_exception`, then the surrounding application will never know about the exceptions...

**Comment by seamusabshere** [comment]
@michaelklishin 

i don't still don't see any argument that hutch's internal thread pool should hide exceptions.

(in other words, if hutch doesn't set `a_o_e`, then an app developer will have to **know** that hutch dies silently on Exceptions. that wasn't the case with us, we had to do a lot of digging to figure out where the zombies were coming from. if you do set `a_o_e`, then at least the exception is immediately visible.)

**Comment by seamusabshere** [comment]
sorry for getting excited about this :)

here's a more appropriate PR https://github.com/ruby-amqp/bunny/pull/381

**Comment by michaelklishin** [comment]
@seamusabshere look, I'm getting a bit tired of this. There are things that libraries are simply not supposed to cover for you because they have 0 context about what a particular app's needs are. Exception handling is one of those things. Yes, it would be great to have more visibility into unhandled exceptions for Bunny or Hutch users. No, we cannot assume that setting `Thread#abort_on_exception` from a library is safe. If you think it is, then set `Thread.abort_on_exception` (the global version) in your own code (e.g. a file that Hutch loads).

Modifying https://github.com/gocardless/hutch/blob/master/lib/hutch/worker.rb#L121 is still on the table because sometimes rescuing `StandardError` only is an oversight. However, rescuing all exceptions is certainly discouraged by some community members, so it's not a no-brainer to me either.

**Comment by seamusabshere** [comment]
*Let me apologize for hitting you with N rapid-fire comments. I haven't been respectful of your time.*

> Exception handling is one of those things.

I agree - I do not want to add ANY exception handling.

> No, we cannot assume that setting Thread#abort_on_exception from a library is safe

I would be happy to drop this if I understood what the argument is for letting internal hutch threads stop (or as I annoyingly called it "go zombie") until they are all dead. Then what? Hutch stays alive but all of its threads are stopped... nobody is notified... what am I missing?

**Comment by michaelklishin** [comment]
@seamusabshere you are missing the fact that setting `Thread#abort_on_exception` from a library is not safe in the general case. We cannot force it down every single Hutch user's throat.

The best I can suggest is adding a configuration option to Bunny. It already has some for opinionated users.

**Comment by dkastner** [comment]
@seamusabshere another argument against `Thread#abort_on_exception` is that while your hutch app may be simultaneously processing several messages, if one thread causes the app to exit because of Exception, then all the other worker threads have to abort. It's better to `rescue Exception` at the top level of the worker thread as we've been discussing.

**Comment by seamusabshere** [comment]
i can see how rescuing Exception there would make sense.

still, as i have perhaps repeated too often, the prime evil is when something hangs silently. i would prefer 1000 jobs dying noisily to 1 dying silently :)
