### ISSUE TITLE
Daemon mode doesn't work on JRuby

### ISSUE THREAD

**Issue by geovanisouza92** [gocardless/hutch#211]
I got this error when trying to use the `daemonize` option on a consumer running in JRuby:

```sh
NoMethodError: undefined method `daemon' for Process:Module
    run at /usr/local/bundle/gems/hutch-0.21.0-java/lib/hutch/cli.rb:16
  <top> at /usr/local/bundle/gems/hutch-0.21.0-java/bin/hutch:7
   load at org/jruby/RubyKernel.java:955
  <top> at /usr/local/bundle/bin/hutch:16
```

Apparently, [JRuby's Process](http://jruby.org/apidocs/org/jruby/RubyProcess.html#detach(org.jruby.runtime.ThreadContext,%20org.jruby.runtime.builtin.IRubyObject,%20org.jruby.runtime.builtin.IRubyObject)) class doesn't support this method. Maybe there is a cross-platform alternative?

**Comment by michaelklishin** [comment]
I am not sure (and doubt it).

**Comment by olleolleolle** [comment]
If there's no support - is that something to document or something to throw specific errors about?

**Comment by michaelklishin** [comment]
@olleolleolle yeah, I think that's the best we can do, at least short term.
