### ISSUE TITLE
Docs: Ensure published version uses the yard extension

### ISSUE THREAD

**Issue by olleolleolle** [gocardless/hutch#223]
We can generate YARD API docs, but when others do it, do they use our addons? Be sure that the standard invocation generates the right thing at rubydocs sites.

**Comment by olleolleolle** [comment]
Update: No, the rubydocs sites do not take the addons in this project. They work, but they're non-standard. Publishing somewhere - like Github Pages, if that's a thing, would make this not a problem. 

Especially the Config stuff is nifty to have generated.

**Comment by olleolleolle** [comment]
Should we instead generate a README section on the Config options?

**Comment by michaelklishin** [comment]
@olleolleolle we can try and see how well it works out.

**Comment by olleolleolle** [comment]
@michaelklishin I should test-run the YARD thing and see what output I can get my hands on. Should be pastable.

**Comment by olleolleolle** [comment]
Closing this, in favor of discussing further in #258.
