### ISSUE TITLE
Send message headers in error handlers

### ISSUE THREAD

**Issue by gottfrois** [gocardless/hutch#225]
Thanks for the great work, glad to see new commits making their way through :)

We use Honeybadger error handler and we would like to have message headers in the context. Currently there is only the message id.

Thanks!

**Comment by olleolleolle** [comment]
@gottfrois Your fix from August got merged - can this issue now be closed?

https://github.com/gocardless/hutch/blob/master/lib/hutch/error_handlers/honeybadger.rb#L18

**Comment by gottfrois** [comment]
Looks like it :)
