### ISSUE TITLE
Config.log_level, Config.log_level= is undefined in 0.22

### ISSUE THREAD

**Issue by sldblog** [gocardless/hutch#232]
We're getting `log_level` related errors if we try `0.22`, eg.

```
     NoMethodError:
       undefined method `log_level' for Hutch::Config:Module
     # ./vendor/bundle/ruby/2.0.0/gems/hutch-0.22.0/lib/hutch/logging.rb:15:in `setup_logger'
     # ./vendor/bundle/ruby/2.0.0/gems/hutch-0.22.0/lib/hutch/logging.rb:21:in `logger'
     # ./vendor/bundle/ruby/2.0.0/gems/hutch-0.22.0/lib/hutch/logging.rb:29:in `logger'
```

Looking at the [diff](https://github.com/gocardless/hutch/compare/v0.21.0...v0.22.0), it seems the configuration changes (`string_setting`, etc.) have not exposed `log_level` or `log_level=`. The first time these are defined is when `Hutch::Config` gets initialised which seems to be too late for the following use cases.

**Steps to reproduce**
```
$ gem install hutch
Successfully installed hutch-0.22.0
1 gem installed

$ hutch -v
/Users/davidlantos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hutch-0.22.0/lib/hutch/cli.rb:176:in `block (2 levels) in parse_options': undefined method `log_level=' for Hutch::Config:Module (NoMethodError)
	from /Users/davidlantos/.rbenv/versions/2.3.1/lib/ruby/2.3.0/optparse.rb:1571:in `block in parse_in_order'

$ ruby -e 'require "hutch"; Hutch::Logging.logger.info("Hello")'
/Users/davidlantos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hutch-0.22.0/lib/hutch/logging.rb:15:in `setup_logger': undefined method `log_level' for Hutch::Config:Module (NoMethodError)
	from /Users/davidlantos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hutch-0.22.0/lib/hutch/logging.rb:21:in `logger'
	from -e:1:in `<main>'
```

**Comment by sgerrand** [comment]
👋  @petehamilton @michaelklishin: Would you please review this report.

**Comment by michaelklishin** [comment]
I can reproduce this with `hutch -v` but not by running an example app that uses Hutch.

**Comment by sldblog** [comment]
💭 The latter case seems to be limited to a use case where `Hutch::Logging.logger` is used before `Hutch::Config.initialize` has a chance to run.

**Comment by michaelklishin** [comment]
@sldblog @sgerrand try master.

**Comment by sldblog** [comment]
@michaelklishin `master` works perfectly, thanks. Do you plan to release it as `0.22.1`?

**Comment by sldblog** [comment]
Fixed in `master`.

**Comment by michaelklishin** [comment]
Yeah, I will release `0.22.1` and yank `0.22.0`. Thanks for reporting.

**Comment by michaelklishin** [comment]
OK, done.
