### ISSUE TITLE
Hutch::CLI not requiring file

### ISSUE THREAD

**Issue by teodor-pripoae** [gocardless/hutch#233]
I'm having the latest version `0.22.1`

My file `foo.rb`

```ruby
require 'hutch'

raise "foo"
```

```
$ hutch --require foo.rb
2016-06-09T16:38:51Z 522 INFO -- hutch booted with pid 522
2016-06-09T16:38:51Z 522 INFO -- connecting to rabbitmq (amqp://guest@127.0.0.1:5672/)
W, [2016-06-09T16:38:51.256043 #522]  WARN -- #<Bunny::Session:0x7ff12f3f9ff8 guest@127.0.0.1:5672, vhost=/, addresses=[127.0.0.1:5672]>: Could not establish TCP connection to 127.0.0.1:5672: Connection refused - connect(2) for 127.0.0.1:5672
2016-06-09T16:38:51Z 522 ERROR -- amqp connection error: could not establish tcp connection to any of the configured hosts
2016-06-09T16:38:51Z 522 FATAL -- couldn't connect to rabbitmq at amqp://guest@127.0.0.1:5672/. Check your configuration, network connectivity and RabbitMQ logs.
2016-06-09T16:38:51Z 522 INFO -- hutch terminated due to an error
```

I debugged the problem and it seems that the logger is initializing config again after `require_paths` was loaded.

Hutch config gets `require_paths` loaded from argv [here](https://github.com/gocardless/hutch/blob/master/lib/hutch/cli.rb#L15). Then the logger gets initialized [here](https://github.com/gocardless/hutch/blob/master/lib/hutch/cli.rb#L21).  It is running the initialize method again and forgets about require paths [here](https://github.com/gocardless/hutch/blob/master/lib/hutch/logging.rb#L14).

On previous versions (0.21.0) it raises error when requiring this file (as expected). In the required file I'm setting Hutch config (mq_host, etc), but with the latest version it is only using the default config.

Using hutch 0.21.0 (this exception is expected).
```
$ hutch --require foo.rb
2016-06-13T15:17:39Z 12 INFO -- hutch booted with pid 12
2016-06-13T15:17:39Z 12 INFO -- requiring 'foo.rb'
/azk/chat/foo.rb:2:in `<top (required)>': foo (RuntimeError)
	from /azk/bundler/ruby/2.3.0/gems/hutch-0.21.0/lib/hutch/cli.rb:44:in `require'
	from /azk/bundler/ruby/2.3.0/gems/hutch-0.21.0/lib/hutch/cli.rb:44:in `block in load_app'
	from /azk/bundler/ruby/2.3.0/gems/hutch-0.21.0/lib/hutch/cli.rb:35:in `each'
	from /azk/bundler/ruby/2.3.0/gems/hutch-0.21.0/lib/hutch/cli.rb:35:in `load_app'
	from /azk/bundler/ruby/2.3.0/gems/hutch-0.21.0/lib/hutch/cli.rb:22:in `run'
	from /azk/bundler/ruby/2.3.0/gems/hutch-0.21.0/bin/hutch:7:in `<top (required)>'
	from bin/hutch:16:in `load'
	from bin/hutch:16:in `<main>'
```

Any ideas ?

Thanks,
Teodor

**Comment by teodor-pripoae** [comment]
Updated the issue to show the previous behaviour (hutch `0.21.0`).

**Comment by michaelklishin** [comment]
It can be another manifestation of the issue with config needing to
self-init. Feel free to take a look into a PR.

On Mon, Jun 13, 2016 at 6:20 PM, Teodor Pripoae <notifications@github.com>
wrote:

> Updated the issue to show the previous behaviour (hutch 0.21.0).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gocardless/hutch/issues/233#issuecomment-225613644>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAEQn3qFJfuc8gyl3lHbC7RcCIU7Ognks5qLXUqgaJpZM4IyLxP>
> .
>



-- 
MK

Staff Software Engineer, Pivotal/RabbitMQ

**Comment by teodor-pripoae** [comment]
The issue was introduced [here](https://github.com/gocardless/hutch/commit/6bd0cc8055ae17404c553da2bcecc687d57d4ee5), I think.

Is there any reason why it needs to be re-initialized ? I'm using hutch both started from the command line using `hutch --require ...` and as a library and never had problems with the config.

If I know the use case, I may find a fix and come out with a PR, but right now I'm clueless.

**Comment by michaelklishin** [comment]
`Hutch::Config` dynamically defines its setters from a map of known keys. This was introduced in https://github.com/gocardless/hutch/commit/b96f4c22e76f3a76a11892df3604ef7322655877 and the commit message says it was to simplify testing with mocks/stubs.

**Comment by michaelklishin** [comment]
The issue was not introduced in https://github.com/gocardless/hutch/commit/6bd0cc8055ae17404c553da2bcecc687d57d4ee5. See #232. The real issue is that dynamic config initialization trips up more things than originally expected.

**Comment by teodor-pripoae** [comment]
Ok, so `Config.initialize` should check if it was already initialized then ?

```ruby
def self.initialize(params = {})
  @config ||= default_config 
  @config.merge!(env_based_config).merge!(params)
  define_methods
  @config
end
```

**Comment by olleolleolle** [comment]
@teodor-pripoae Something like that would be quite good. That very first ||= seems well-placed. 

When reinitializing, any specific config - perhaps set using a dynamically-defined method, will be lost. 

Perhaps more should be covered by the ||=?

**Comment by olleolleolle** [comment]
Oh, I may be all wrong. It's late in the day. A test could prove this!

**Comment by olleolleolle** [comment]
@michaelklishin I returned to this thing yesterday. Latest released hutch still has the issue that Hutch::Config.initialize isn't run at definition-time. I pegged my solution's Gemfile to a slightly newer, specific commit in GitHub, and that began working.

The situation could be described as: MarchHare is only ever getting default settings, never hearing about the configuration.

**Comment by olleolleolle** [comment]
@teodor-pripoae Can you re-test with latest?

**Comment by teodor-pripoae** [comment]
Yes, it works. Thank you!

**Comment by olleolleolle** [comment]
@teodor-pripoae Glad to hear it's working for you! 🎉  

Can you mark this Issue closed, now?
