### ISSUE TITLE
Logger resets Hutch configuration

### ISSUE THREAD

**Issue by HGebhardt** [gocardless/hutch#240]
We are using Hutch within an Rails application and we have a problem with producers if we doesn't setup the logger in the initializer.
The following is not working:
`Hutch::Config.set(:mq_exchange, 'name')`

This works:
```
Hutch::Logging.logger = Rails.logger
Hutch::Config.set(:mq_exchange, 'name')
```

The problems seems to be [line 14 in logging.rb](https://github.com/gocardless/hutch/blob/v0.22.1/lib/hutch/logging.rb#L14). If you set the logger in the initializer the whole method `setup_logger` is not called.
I don't know if it's needed to load the default setup or if you could merge an existing configuration in `config.rb initialize`.

**Comment by michaelklishin** [comment]
@HGebhardt can you please try #241?

**Comment by michaelklishin** [comment]
Should be fixed in master. Please give it a try?
