### ISSUE TITLE
Dynamically picking version of ActiveSupport won't work as expected

### ISSUE THREAD

**Issue by jensnockert** [gocardless/hutch#244]
https://github.com/gocardless/hutch/commit/814c1e852c044e9d7278490115841f5870886efc sets the ActiveSupport version at Gem build time, so will pick dependency depending which RUBY_VERSION it was built on, not what RUBY_VERSION it is installed on. :/

I'm not sure what the best way to actually solve this issue is. I'll try to catch @olleolleolle and send in a proper.

**Comment by jensnockert** [comment]
An extension like the following 'works', except if you use Bundler which won't pick up the dependency.

```ruby
require 'rubygems/dependency_installer.rb'

begin
  activesupport_version = (RUBY_VERSION >= '2.3' ? '>= 4.0' : '~> 4.0')

  installer = Gem::DependencyInstaller.new
  installer.install 'activesupport', activesupport_version
rescue
  exit(1)
end

f = File.open(File.join(File.dirname(__FILE__), "Rakefile"), "w")
f.write("task :default\n")
f.close
```

**Comment by michaelklishin** [comment]
This Ruby version dependency stuff is depressing.

**Comment by olleolleolle** [comment]
Let me express it with a `:-|` neutral emoji face. 

We're all in this together.

**Comment by jensnockert** [comment]
https://github.com/bundler/bundler/issues/4960 is maybe relevant?

**Comment by michaelklishin** [comment]
I hope this was addressed by a bunch of PRs in master that uses separate Gemfiles for CI and drops the version constraint from Active Support (which should be fine, this gem's needs are small).

**Comment by jensnockert** [comment]
Yes.
