### ISSUE TITLE
pidfile not getting generated

### ISSUE THREAD

**Issue by tusharmaroo** [gocardless/hutch#268]
`hutch 0.23.1` with `rails 4.2.6` , it is not able to generate PID file. 
I am using the below configuration in initializers
`Hutch::Config.set(:pidfile, "tmp/pids/hutch.pid")`

**Comment by michaelklishin** [comment]
It's very difficult to suggest much without having any logs provided but it sounds like you want "/tmp/pids/hutch.pid" (with a leading slash).

**Comment by michaelklishin** [comment]
Also, do you run Hutch as a daemon or in foreground? is it loaded as part of a Rails process as a daemon?

**Comment by tusharmaroo** [comment]
@michaelklishin  
I am trying to run it as a daemon as per the readme. It's not working.
`Hutch::Config.set(:daemonise, true)`

But when i try to run daemon or pidfile by cli it works.
`hutch -d --pidfile=tmp/pids/hutch.pid`

It picks up using [this](https://github.com/gocardless/hutch/blob/master/lib/hutch/cli.rb#L15)
Initializer is not picking some of the values such as daemonise & pidfile [here](https://github.com/gocardless/hutch/blob/master/lib/hutch/cli.rb#L14)

This might be a bug?

**Comment by michaelklishin** [comment]
@tusharmaroo what *exactly* are you doing and what is the goal? You are not specifying a leading slash in your pid file path — is this intentional?

Hutch has a standalone daemon. It also has a "library" part that's often used from Web apps.

**Comment by tusharmaroo** [comment]
@michaelklishin Yes, the pid file is intentional. as i have all my pids in the same folder.
I am trying to run hutch without using any additional CLI parameters,
yet expecting it to create a PID file & run as a daemon. Because I have put those settings in the rails initializers from there it gets loaded in the system. I am able to see mq_exchange, mq_host etc getting updated based on my settings but not PID file & daemonize. I will try to get you more details in sometime.

**Comment by michaelklishin** [comment]
I was asking if the missing leading slash is intentional.

**Comment by michaelklishin** [comment]
@tusharmaroo so you are trying to load Hutch inside of Rails and expect it to daemonize? or do you run `hutch` the binary but expect it to load your initializer? Then it is too late as all the config settings have long been loaded.

This is why I asked what *exactly* (step by step, as detailed as possible) you are doing. There is a CLI switch that controls whether Hutch should daemonize: have you considered using it instead of relying on Ruby files that may or may not be loaded by the time Hutch makes this decision?

**Comment by vitornogueira** [comment]
I have the same issue.

When I set pidfile with:

```ruby
Hutch::Config.set(:pidfile, 'tmp/pids/hutch.pid')
```

the pidfile is not created. But when I set pidfile with cli it works:

```shell
hutch --pidfile=tmp/pids/hutch.pid
```

**Comment by michaelklishin** [comment]
A very likely reason for that is that the config is loaded and evaluated after the pid file is created.
