### ISSUE TITLE
Cut a new Hutch release

### ISSUE THREAD

**Issue by damien** [gocardless/hutch#285]
Hey guys!

Looking at the changes since [v0.24.0](https://github.com/gocardless/hutch/compare/v0.24.0...master), it seems there's a bunch of cool work that's not yet available via Rubygems. I'm personally interested in support for newer versions of the HB API.

Any chance we get all this goodness available on Rubygems as v0.25.0?

**Comment by michaelklishin** [comment]
I've publisehd [an RC](https://rubygems.org/gems/hutch) for starters.

**Comment by damien** [comment]
Excellent, thanks @michaelklishin! I can close this ticket or resolve it once 0.25.0 is out of RC. What would you prefer?

**Comment by michaelklishin** [comment]
I was going to close it when we release a GA.

**Comment by damien** [comment]
Will do, I look forward to it!
