### ISSUE TITLE
Connection error not reported to sentry

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [gocardless/hutch#288]
I'm wondering if there is any reason for the following error not being handled by the error handlers.

https://github.com/gocardless/hutch/blob/db5e5f34c9da7818c044e0857c321ad8c2185b61/lib/hutch/cli.rb#L93

I would like to see for instance connection problems at start-up reported by `sentry`.

If there is no reason for using the error handlers, I would love to submit a merge request.

**Comment by michaelklishin** [comment]
It's been around since #9, so since very early days. It makes sense to collect those errors. Unless anyone objects, I'd say go ahead and submit a PR. We can discuss the downsides of this change there.
