### ISSUE TITLE
Architecture decision re: Single Channel

### ISSUE THREAD

**Issue by bradrobertson** [gocardless/hutch#295]
This is more of a question than anything so it maybe be more appropriate in a mailing list but I didn't see one on the readme.

I'm just looking through the implementation and noticed that Hutch uses a single channel for all communication to rabbitmq. My understanding is that channels shouldn't be shared across threads, but the implementation in Hutch leads me to believe that concurrent calls to `Hutch.publish` would be done over the same channel.

Is this a concern? Is there a possibility of re-architecting the Hutch broker to issue channels from a pool that each thread can use?

If nothing is to change, should the Readme be updating specifying potential thread safety concerns?

I'm not entirely sure what the implications of multiple threads communicating over the same channel are as I don't fully understand the underlying protocol.

**Comment by michaelklishin** [comment]
`Hutch.publish` can be used from multiple threads but it requires explicit synchronisation (see [Bunny documentation](http://rubybunny.info/articles/concurrency.html)). I’m not sure how this API can be rearchitected for multiple channels. For consumers it should be quite easy but publishing with a single class method will run either into the need to manually synchronise or a way to deal with race conditions between publishes on different channels in a pool.

A README note with a link to Bunny’s doc guide on concurrency is a good idea.

This [rabbitmq-users post](https://groups.google.com/d/msg/rabbitmq-users/u4AZ2t9enu0/WkDIU9ENAgAJ) explains why concurrent publishing on a shared channel requires synchronisation.
