### ISSUE TITLE
Can hutch use fanout exchange?

### ISSUE THREAD

**Issue by SmrutiSuman** [gocardless/hutch#299]
I want to use fanout exchange using hutch, is there any way to use it?

**Comment by michaelklishin** [comment]
Instantiate a [publisher](https://github.com/gocardless/hutch/blob/master/lib/hutch/publisher.rb#L10) directly or use Bunny channel.

**Comment by SmrutiSuman** [comment]
@michaelklishin  Below is my code.

`require 'hutch'

class OfferPublisher

  ROUTING_KEY = '*.*.#'.freeze

  def self.publish(message)
    Hutch.connect
    Hutch.publish(ROUTING_KEY, message)
  end
end
`

**Comment by michaelklishin** [comment]
@SmrutiSuman see server logs and consider posting *the entire* stack trace. Help others help you.

**Comment by michaelklishin** [comment]
Also, there is *absolutely no need* to connect each time you need to publish a message. All protocols supported by RabbitMQ assume long-lived connections. Lastly, even if that somehow was necessary in this case, your code connects and never closes the connection, thus leaking it.
