### ISSUE TITLE
Question: Hutch.connect usage

### ISSUE THREAD

**Issue by egze** [gocardless/hutch#311]
Hi,

Don't know a better way to talk about the Hutch gem. Do you have any Slack/IRC/whatever channel?

Anyway, I was wondering what is the best way to call `Hutch.connect` in a Rails app? Just put it in the `initializers`? I can see it being a problem if RabbitMQ is not running at that moment. Is there a better way?

Thanks

**Comment by michaelklishin** [comment]
Everything that [applies to Bunny](http://rubybunny.info/articles/connecting.html#connecting_in_web_applications_ruby_on_rails_sinatra_etc) should be very much applicable to Hutch.

[RabbitMQ community Slack channel](http://www.rabbitmq.com/#community) and [Bunny mailing list](https://groups.google.com/forum/#!forum/ruby-amqp) is the closest thing there is for Hutch.

**Comment by michaelklishin** [comment]
RabbitMQ's own mailing list can be used as well, of course.
