### ISSUE TITLE
 Multi channels support per connection

### ISSUE THREAD

**Issue by bazinga012** [gocardless/hutch#317]
From channel.rb in bunny gem: AMQP 0.9.1 is a multi-channeled protocol. Channels provide a way to multiplex a heavyweight TCP/IP connection into several light-weight connections.

But hutch doesn't seem to do that, I mean hutch uses a single channel per connection, why is that? 
PS: Sorry if I'm missing something basic.

**Comment by michaelklishin** [comment]
Because sharing a TCP connection between processes is very problematic at best (and impossible up to certain Linux kernel versions).
