### ISSUE TITLE
Cut a new hutch release

### ISSUE THREAD

**Issue by junedkazi** [gocardless/hutch#324]
It has almost been a year since the last release was done. We have quite a few PR's being merged since then. I was wondering if it is time to cut a new release.

**Comment by michaelklishin** [comment]
Makes sense.

**Comment by junedkazi** [comment]
@michaelklishin thank you for a quick response. Do you have a timeline in mind when you plan on cutting the next release ?

**Comment by michaelklishin** [comment]
[0.26.0 is out](https://rubygems.org/gems/hutch) now.

**Comment by junedkazi** [comment]
Thank you !!!
