### ISSUE TITLE
Requeue method is closing channel 

### ISSUE THREAD

**Issue by mariacastro96** [gocardless/hutch#330]
I was trying to requeue and I realized everytime I requeue the worker was sending an ack after requeue. This was disconnecting the channel, making it impossible to access the messages in the queue again. Would only requeue the 1st one and then the connection was crashing. 

Did anyone experience a similar situation?

Thanks in advance

**Comment by michaelklishin** [comment]
Please see server logs. Almost certainly the channel is closed due to a [double ack](https://www.rabbitmq.com/confirms.html#consumer-acks-double-acking).

**Comment by michaelklishin** [comment]
FTR, the connection is not affected by double acks. It's a [channel-level exception](https://www.rabbitmq.com/channels.html#error-handling).

**Comment by mariacastro96** [comment]
@michaelklishin thanks for the reply. 

in fact, instead of an ack it was a nack that was automatically being sent when am error was being raised. so by default, the error exception was sending a nack (sorry for the confusion). 

https://github.com/gocardless/hutch/blob/9314b3b8c84abeb78170730757f3eb8ccc4f54c5/lib/hutch/worker.rb#L92

    def acknowledge_error(delivery_info, properties, broker, ex)
      acks = error_acknowledgements +
        [Hutch::Acknowledgements::NackOnAllFailures.new]
      acks.find do |backend|
        backend.handle(delivery_info, properties, broker, ex)
      end
    end

So when the `requeue!` is called in the code, the connection breaks because after the requeue the nack is called. 

Our solution is adding adding our 'custom' error acknowledgement doing the requeue inside of it. So by default instead of a nack we are sending a requeue.

Do you think it makes sense to mention in the documentation that a nack is always being called (when there is an exception) regardless? Or do you have a better idea to solve this problem? 

Thanks in advance

**Comment by michaelklishin** [comment]
@mariacastro96 acks are not different from nacks when it comes to double acknowledgements. Please inspect and share relevant server log snippets. I highly doubt that "the connection breaks". What you get is a [channel-level exception](https://www.rabbitmq.com/channels.html#error-handling) (which closes the channel so it can no longer be used).

If it's the default exception handler that does the second acknowledgement (with a `nack`), using a custom exception handler is one option. Another is to handle exceptions in your own code, as [consumers are generally expected to](https://github.com/ruby-amqp/rubybunny.info/commit/80364589377e2e3a1d48e6963ff8f77c93df5ae9) with Bunny and most clients. Documenting this for Hutch is a good idea, please submit a PR.
