### ISSUE TITLE
Enable Lazy mode for queues

### ISSUE THREAD

**Issue by arthurmde** [gocardless/hutch#340]
It would be interesting if Hutch offered options to set the consumers' queues as [lazy](https://www.rabbitmq.com/lazy-queues.html) through an option such as `queue_name`.

[Lazy queues are recommended in some use cases.](https://www.cloudamqp.com/blog/2017-12-29-part1-rabbitmq-best-practice.html#enable-lazy-queues-to-get-predictable-performance)

**Comment by arthurmde** [comment]
I can provide a PR if it is in the scope of the project ;)

**Comment by michaelklishin** [comment]
@arthurmde yes, absolutely. Please do! Thank you!

**Comment by michaelklishin** [comment]
While at it we should support [quorum queues](https://www.rabbitmq.com/quorum-queues.html). Since both use optional queue arguments (queue type does not support policies as it cannot be changed at runtime), it makes sense to add support for both at once.

**Comment by michaelklishin** [comment]
Note that #348 undoes some of the defaults for Hutch `1.0` because it breaks backwards compatibility for some installations.
