### ISSUE TITLE
Hutch URI supported?

### ISSUE THREAD

**Issue by jnarowski** [gocardless/hutch#350]
I see references to URI in the code, but it's not supported at the command line? I have RABBITMQ_URL set as an env var and would be nice to not have to break it up into several ENV vars needed for username, password etc.

**Comment by michaelklishin** [comment]
Hutch uses a config file (or `Hutch::Config` modifications) which has a [`uri` property](https://github.com/gocardless/hutch/blob/master/lib/hutch/config.rb#L66) used when [connection parameters are computed](https://github.com/gocardless/hutch/blob/727c9f22386c8a4284f813823d8212dc37b2bd59/lib/hutch/broker.rb#L284).

Environment variables are not really used by Hutch and only sparingly in Bunny (e.g. `BUNNY_LOG_LEVEL`).

**Comment by jnarowski** [comment]
Would you be open to a pull request that adds URI as a possible command line option?

**Comment by michaelklishin** [comment]
Sure. Thank you for considering a contribution!
