### ISSUE TITLE
Hutch concurrency question

### ISSUE THREAD

**Issue by jnarowski** [gocardless/hutch#352]
I launched hutch on our kuberneties cluster, and it looks like only one of the containers is picking up jobs. Is hutch limited to a single topic subscription for consuming messages, or is this just a config issue on my side? 

I didn't see any threading or worker option config aside from **consumer_pool_size**

**Comment by michaelklishin** [comment]
Hutch, Bunny and RabbitMQ absolutely do not have this limitation. Multiple consumers on a shared queue become competing consumers. Assuming there are several pods running Hutch consumers and enough messages ready for delivery, you will get parallel (uncoordinated) processing between them.

Please see [tutorial 2](https://www.rabbitmq.com/tutorials/tutorial-two-ruby.html) and these RabbitMQ guides: [Queues](https://www.rabbitmq.com/queues.html), [Consumers](https://www.rabbitmq.com/consumers.html), [Concepts Overview](https://www.rabbitmq.com/tutorials/amqp-concepts.html).

**Comment by sldblog** [comment]
Not sure if this helps, but might be useful for context.

In the past (please see context below), we had to configure the bit in [tutorial 2](https://www.rabbitmq.com/tutorials/tutorial-two-ruby.html) about "Fair dispatch", and we ended up setting [`channel_prefetch`](https://github.com/gocardless/hutch/blob/v0.28.0/lib/hutch/config.rb#L80-L81) to 16. The trade-off of having queue sizes grow during spikes was acceptable to us.

We were working with "heavy" (long-running) consumers, and usually one of the consumers ended up too busy, which sounds similar to your situation.

**Comment by jnarowski** [comment]
Thanks for the feedback. We'll dig in now.

**Comment by michaelklishin** [comment]
The prefetch value has throughput and (client side) concurrency effects. See [Consumer Acknowledgement Modes, Prefetch and Throughput](https://www.rabbitmq.com/confirms.html#channel-qos-prefetch-throughput) and [this old but still relevant blog post](https://www.rabbitmq.com/blog/2014/04/14/finding-bottlenecks-with-rabbitmq-3-3/).

For a project such as Hutch, the value of `1` is not great but most predictable (no unexpected natural race conditions between consumers). In the end some projects such as Spring AMQP concluded that the default of `1` was a massive net negative and changed the default to something like `128` (the exact value is not very important). We'd consider doing the same for Hutch if necessary.
