### ISSUE TITLE
Handing database connection timeouts

### ISSUE THREAD

**Issue by igatto** [gocardless/hutch#354]
Let's say I have a pretty strict timeouts inside my database.yml file:
```
  connect_timeout: 5
  wait_timeout: 5
  read_timeout: 5
  write_timeout: 5
  interactive_timeout: 5
  timeout: 5
```

And after 5 seconds of being idle when Hutch is trying to process a new payload. I have this error:
```
ActiveRecord::StatementInvalid - Mysql2::Error::ConnectionError: MySQL server has gone away
```

How should I refresh connection to the database?

**Comment by michaelklishin** [comment]
This is a fantastic question for an ActiveRecord forum. Neither Hutch nor Bunny have any restrictions or opinion on this.
