### ISSUE TITLE
Run only some consumers

### ISSUE THREAD

**Issue by andrykonchin** [gocardless/hutch#355]
I am wondering whether there is a way to run only some consumers in a Rails application.

The goal is to scale consumers independently and run certain consumers only on some certain instances.

There is a `require` option but it just registers a consumer again. `autoload-rails` isn't helpful as far as our consumers use Rails stuff.

**Comment by michaelklishin** [comment]
Hutch assumes that all consumers it can discover should run. Restricting discovery one way or another is what you want.

**Comment by netrusov** [comment]
@andrykonchin seems like `--only-group` option is what you are looking for. but before that you must configure consumer groups in `hutch.yml`:

```yaml
consumer_groups:
  analytics:
    - AnalyticsConsumer
  # ... etc
```

I'm using this combined with systemd (docker will work great too) to run as many instances of specific consumers as I want

**Comment by andrykonchin** [comment]
Thank you @netrusov . Wondering why this option isn't documented and maintainers aren't aware of it.

**Comment by michaelklishin** [comment]
@andrykonchin Hutch is open source software, so if something isn't up to your liking, you are welcome to contribute to it, including documentation.

I maintain dozens of projects and cannot remember every single contribution to every single one of them.
[`--only-group` specifically was introduced in early 2018](https://github.com/ruby-amqp/hutch/blob/dce6009450c6e4a03a559ea81dcd7c900ae70042/CHANGELOG.md#0250---january-17th-2018), so it's been a while.

Hutch could use some additional maintainers. If you'd like to become one and make it better for everyone, let us know.
