### ISSUE TITLE
Why a single topic exchange?

### ISSUE THREAD

**Issue by zeisss** [gocardless/hutch#39]
Hi there!

I just found your project and like it so far. I have just a design question I don't completely understand: Why did you choose to go with a single topic-exchange?

As far as I understand, this limits you, as every message can ever only be consumed by one type (=ClassName) of consumer. And Hutch does not support request-reply calls, which I would take as a reason.

I would assume, creating a separate fanout-exchange for every `consume` statement (your current routing key) and binding them to your consumer queues would make more sense, as this allows a single key to be handled by multiple different consumers.

Example: My web frontend publishes a `user.created` message and I want two separate services acting upon this: `SendWelcomeEmailConsumer` and `DuplicateAccountNotifierConsumer`. 

Is there something I am missing?

**Comment by SmrutiSuman** [comment]
@hmarr So cannot we use fanout exchange in hutch instead of topic exchange?

**Comment by michaelklishin** [comment]
@SmrutiSuman you can obtain a Bunny channel reference and use any exchange type you please. At that point you will be stepping outside of Hutch's opinionated design.

**Comment by tusharmaroo** [comment]
@michaelklishin Hi Michael, I have extended hutch to support all the other exchanges as well. Is it something that we can have optionally in hutch?  I would love to work on a PR. Are we open for looking away from the opinionated design. Thanks.

**Comment by michaelklishin** [comment]
@tusharmaroo thank you for your time. It depends on what that looks like. I doubt significant deviations would be a good fit. Do you have a branch I and others can take a look at?
