### ISSUE TITLE
Consider using March Hare on JRuby

### ISSUE THREAD

**Issue by michaelklishin** [gocardless/hutch#72]
While Hutch works well on JRuby today with recent Bunny versions, one would get several times better throughput if [March Hare](http://rubymarchhare) was used when running on JRuby.

Worth considering, given that MH and Bunny API's are really close.

**Comment by teodor-pripoae** [comment]
Hi,

Related to https://github.com/ruby-amqp/bunny/pull/328#issuecomment-127007716, would you need any help implementing jruby driver using [March Hare](http://rubymarchhare.info/) ?

**Comment by michaelklishin** [comment]
@teodor-pripoae feel free to look into it, that would be appreciated!

**Comment by michaelklishin** [comment]
Fixed in master.
